# Generated by Django 5.2.13 on 2026-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payout",
            name="bank_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
